excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://appleglubz.github.io
title: Awesome
email: 
author: appleglubz
description: My awesome new site hgdfgdjkh gjkdhud g
paginate: 3
google_analytics: 